// Official skills, bundled as text (generated from resources/skills/*.md by
// scripts/bundle-skills.mts — edit the markdown, not this file).
//
// They ship enabled; a user skill with the same name shadows one, and any of
// them can be turned off in Settings. Content is procedural knowledge distilled
// from Chaty's own development: the practices that repeatedly separated a fix
// that held from one that had to be redone.

export const OFFICIAL_SKILL_FILES: { file: string; text: string }[] = [
  { file: "cardlet.md", text: "---\nname: cardlet\ndescription: Turn text into polished carousel card images (PNG) via the Cardlet API\nwhen: the user wants social/carousel cards — 小红书图文卡片, Instagram carousel, shareable card decks — from text or notes\n---\n\nCardlet (https://usecardlet.vercel.app) renders styled carousel cards from\nmarkdown-lite text over plain HTTP — bash + curl only, no browser needed.\n\n1. **Write the deck** to `deck.json` in the workspace. `---` splits cards;\n   one idea per card (heading + 1–3 short lines); EN/中文 both render well.\n\n```json\n{\"deck\":{\"t\":\"Title ≤64\",\"b\":\"Intro\\n---\\n## Point one\\nDetail line.\\n---\\n%% 87% | a big stat card\",\"a\":\"@handle\",\"tp\":\"ink\",\"s\":\"ig45\"}}\n```\n\n   Keys: `t` title · `b` body (`## heading`, `- bullet`, `> quote`,\n   `**bold**`, `==highlight==`, `%% stat | caption`, `---` new card) ·\n   `a` author · `tp` template (free: `ink` `cloud` `noir` `peach`) ·\n   `s` size (`ig45` 1080×1350, `xhs34` 小红书 1242×1656, `sq11` square,\n   `story916`) · optional: `f` text size 0–4, `l` spacing 0–2, `bf`\n   `sans`/`serif`, `c` cover card 0/1, `pn` page numbers 1/0.\n\n2. **Render and save** (first call may take 10–20 s — cold start; retry once\n   on failure):\n\n```bash\ncurl -s --max-time 180 -X POST https://usecardlet.vercel.app/api/render \\\n  -H \"Content-Type: application/json\" -d @deck.json \\\n| python3 -c \"import json,sys,base64; d=json.load(sys.stdin); assert 'images' in d, d; [open(f'card-{i+1:02d}.png','wb').write(base64.b64decode(p)) for i,p in enumerate(d['images'])]; print(d['pages'],'cards saved, watermark:',d['watermark'])\"\n```\n\n3. **Report the saved PNG paths** to the user.\n\nLimits: ≤12 cards per JSON call; for bigger decks fetch one card at a time —\n`GET /api/render?d=p<base64url(deckJSON)>&page=N` returns a single binary PNG.\nBe kind to the free API: sequential calls, no parallel bursts.\n\nPro: if the user gives a Cardlet Pro code (`CDLT.…`), add `\"code\":\"CDLT…\"`\nbeside `\"deck\"` — removes the footer watermark and unlocks pro templates\n(`glass` `sunset` `mint` `press` `pop` `night` `terminal` `sakura` `gold`\n`blueprint` `note`) plus `q` (QR sign-off URL). Without a code, cards carry a\nsmall watermark — say so instead of working around it.\n" },
  { file: "debug-by-mechanism.md", text: "---\nname: debug-by-mechanism\ndescription: Find the mechanism behind a bug instead of pattern-matching a fix\nwhen: something is broken, failing, or behaving unexpectedly\n---\n\nA fix that makes the symptom disappear without explaining it usually moved the\nbug somewhere quieter.\n\n1. **Reproduce it smaller.** Strip the case until one more removal makes the\n   symptom vanish. That boundary is where the mechanism lives.\n2. **Read the code on the failing path** — the actual current source, not your\n   memory of it. Note every place the observed value could come from.\n3. **Name the mechanism in one sentence** before editing anything: \"X happens\n   because Y runs before Z.\" If you can't, you're still guessing.\n4. **Predict something else that must be true** if your explanation is right,\n   then check it. A wrong theory usually fails this step, cheaply.\n5. **Fix the mechanism, not the symptom.** Then confirm the original case, and\n   confirm a neighbouring case that shares the mechanism.\n6. **If two attempts fail**, the mechanism is wrong — go back to step 2 rather\n   than layering another guess on top.\n" },
  { file: "investigate-first.md", text: "---\nname: investigate-first\ndescription: Understand an unfamiliar codebase before changing it\nwhen: starting work in a repo or area you haven't touched yet\n---\n\n1. **Orient once**: `understand_repo` for the shape, then read the build/test\n   commands. Knowing how to run the tests early is what makes every later step\n   verifiable.\n2. **Search by meaning, not by guess**: `search_code` with the behavior you're\n   looking for (\"where uploads are validated\"), then `outline` the files it\n   returns before reading them whole.\n3. **Follow the data, not the names.** Find where the value you care about is\n   produced and where it is consumed; the code in between is the part you\n   actually need to understand.\n4. **Match local conventions** — comment density, naming, error handling. A\n   change that reads like the file around it needs no explanation.\n5. **Check for existing tests of the area** before writing new ones; extend\n   the established pattern rather than introducing a second style.\n" },
  { file: "verify-before-push.md", text: "---\nname: verify-before-push\ndescription: Prove a change works before it leaves the machine\nwhen: the user asks to commit, push, or ship a change\n---\n\nNever push a change whose correctness you have only reasoned about.\n\n1. **Pick the gate that can actually fail.** Type-checkers and linters catch\n   shape errors, not behavior. If the change alters behavior, the gate is a\n   test that fails without your fix and passes with it — write it if it\n   doesn't exist.\n2. **Run the gate and read the output.** Do not infer success from \"no error\n   printed\"; find the pass count or the assertion that proves the new path ran.\n3. **For anything visual or interactive**, capture evidence: a screenshot,\n   a measured pixel value, a page digest. A description of what should happen\n   is not evidence.\n4. **Commit only after the gate is green**, and put what you verified in the\n   commit message — the next reader needs to know which claims were checked.\n5. **If a gate can't be run locally** (another OS, real credentials, a GPU),\n   say so plainly and name what remains unverified. Do not present it as done.\n" },
];
