// Official skills, bundled as text (generated from resources/skills/*.md by
// scripts/bundle-skills.mts — edit the markdown, not this file).
//
// They ship enabled; a user skill with the same name shadows one, and any of
// them can be turned off in Settings. Content is procedural knowledge distilled
// from Chaty's own development: the practices that repeatedly separated a fix
// that held from one that had to be redone.

export const OFFICIAL_SKILL_FILES: { file: string; text: string }[] = [
  { file: "debug-by-mechanism.md", text: "---\nname: debug-by-mechanism\ndescription: Find the mechanism behind a bug instead of pattern-matching a fix\nwhen: something is broken, failing, or behaving unexpectedly\n---\n\nA fix that makes the symptom disappear without explaining it usually moved the\nbug somewhere quieter.\n\n1. **Reproduce it smaller.** Strip the case until one more removal makes the\n   symptom vanish. That boundary is where the mechanism lives.\n2. **Read the code on the failing path** — the actual current source, not your\n   memory of it. Note every place the observed value could come from.\n3. **Name the mechanism in one sentence** before editing anything: \"X happens\n   because Y runs before Z.\" If you can't, you're still guessing.\n4. **Predict something else that must be true** if your explanation is right,\n   then check it. A wrong theory usually fails this step, cheaply.\n5. **Fix the mechanism, not the symptom.** Then confirm the original case, and\n   confirm a neighbouring case that shares the mechanism.\n6. **If two attempts fail**, the mechanism is wrong — go back to step 2 rather\n   than layering another guess on top.\n" },
  { file: "investigate-first.md", text: "---\nname: investigate-first\ndescription: Understand an unfamiliar codebase before changing it\nwhen: starting work in a repo or area you haven't touched yet\n---\n\n1. **Orient once**: `understand_repo` for the shape, then read the build/test\n   commands. Knowing how to run the tests early is what makes every later step\n   verifiable.\n2. **Search by meaning, not by guess**: `search_code` with the behavior you're\n   looking for (\"where uploads are validated\"), then `outline` the files it\n   returns before reading them whole.\n3. **Follow the data, not the names.** Find where the value you care about is\n   produced and where it is consumed; the code in between is the part you\n   actually need to understand.\n4. **Match local conventions** — comment density, naming, error handling. A\n   change that reads like the file around it needs no explanation.\n5. **Check for existing tests of the area** before writing new ones; extend\n   the established pattern rather than introducing a second style.\n" },
  { file: "verify-before-push.md", text: "---\nname: verify-before-push\ndescription: Prove a change works before it leaves the machine\nwhen: the user asks to commit, push, or ship a change\n---\n\nNever push a change whose correctness you have only reasoned about.\n\n1. **Pick the gate that can actually fail.** Type-checkers and linters catch\n   shape errors, not behavior. If the change alters behavior, the gate is a\n   test that fails without your fix and passes with it — write it if it\n   doesn't exist.\n2. **Run the gate and read the output.** Do not infer success from \"no error\n   printed\"; find the pass count or the assertion that proves the new path ran.\n3. **For anything visual or interactive**, capture evidence: a screenshot,\n   a measured pixel value, a page digest. A description of what should happen\n   is not evidence.\n4. **Commit only after the gate is green**, and put what you verified in the\n   commit message — the next reader needs to know which claims were checked.\n5. **If a gate can't be run locally** (another OS, real credentials, a GPU),\n   say so plainly and name what remains unverified. Do not present it as done.\n" },
];
